id: online.anthonyis.scs-rclient
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
command: scs-rclient
finish-args:
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --share=ipc
  - --share=network
  - --filesystem=xdg-documents/scs-rclient:create
  - --filesystem=xdg-config/rclone:ro
modules:
  - name: scs-rclient
    buildsystem: simple
    build-commands:
      - install -Dm755 src-tauri/target/release/scs-rclient /app/bin/scs-rclient
      - install -Dm644 src-tauri/icons/128x128.png /app/share/icons/hicolor/128x128/apps/online.anthonyis.scs-rclient.png
      - install -Dm644 .github/flatpak/online.anthonyis.scs-rclient.desktop /app/share/applications/online.anthonyis.scs-rclient.desktop
    sources:
      - type: dir
        path: ../../
