name: Release Asset Scan

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  virustotal:
    name: VirusTotal Release Asset Scan
    runs-on: ubuntu-latest
    steps:
      - name: Scan Release Assets via VirusTotal
        uses: crazy-max/ghaction-virustotal@v5.0.0
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            .exe$
            .flatpak$
          request_rate: 2
